apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongodb
spec:
  replicas : 1
  template :
    metadata:
     name: mongodb
     labels:
       app: mongodb
    spec:
      containers:
       - name: mongodb
         image: mongo:3.6.5-jessie
         volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name : mongo-volume
          hostPath:
            path:  /home/arshabbir/mongo/db
            type: DirectoryOrCreate
  selector:
    matchLabels:
       app: mongodb



---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: mongodb

  ports:
    - name: http
      port: 27017

  type: ClusterIP


