apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: kube-system
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some new/directory/structure/"
    type: DirectoryOrCreate


